version: "3.9"

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - ${APP_PORT}:80
    volumes:
      - ./web:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql



  php:
    container_name: php
    build:
      dockerfile: ./docker/php/Dockerfile
      context: .
    volumes:
      - ./web:/var/www/html
    entrypoint: [ "sh", "/docker/php/entrypoint.sh" ]
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mysql:latest
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker/data/mysql:/var/lib/mysql
